### ISSUE TITLE
We need an API that returns all the conversation of particular user

### ISSUE THREAD

**Issue by aramo2000** [Mgrdich/LLM_service#16]
we need to develop an API endpoint that retrieves all conversations associated with a particular user. Through it, the clients will be able to fetch the complete history of conversations for a specified user, for example, viewing past messages and analyzing user engagement.

Expected Outcome:
An API endpoint that retrieves and delivers all conversations related to a specific user, enabling advanced user interaction analytics.

**Comment by Mgrdich** [comment]
This needs to be done , when the whole user functionality is plugged in.
